service: default
env: flex
runtime: python
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT nfl-demo:app

runtime_config:
  python_version: 3

automatic_scaling:
  # min_num_instances: 1
  max_num_instances: 4

resources:
  cpu: 1
  memory_gb: 1.
  disk_size_gb: 10
